// This file was automatically generated by the 'make_oid_table' program

#include "oid_search.h"
#include "oid_const.h"

using namespace oid;

struct oid_search_node
{
 int id;
 int count;
 const struct oid_search_link *links;
};

struct oid_search_link
{
 unsigned byte;
 const oid_search_node *next;
};

static const oid_search_node n99    = { ID_AT_DOMAIN_COMPONENT, 0, NULL }; // 0.9.2342.19200300.100.1.25
static const oid_search_link sl98[] = { { 25, &n99 } };
static const oid_search_node n98    = { 0, 1, sl98 };
static const oid_search_link sl97[] = { { 1, &n98 } };
static const oid_search_node n97    = { 0, 1, sl97 };
static const oid_search_link sl96[] = { { 100, &n97 } };
static const oid_search_node n96    = { 0, 1, sl96 };
static const oid_search_link sl95[] = { { 44, &n96 } };
static const oid_search_node n95    = { 0, 1, sl95 };
static const oid_search_link sl94[] = { { 242, &n95 } };
static const oid_search_node n94    = { 0, 1, sl94 };
static const oid_search_link sl93[] = { { 147, &n94 } };
static const oid_search_node n93    = { 0, 1, sl93 };
static const oid_search_link sl92[] = { { 137, &n93 } };
static const oid_search_node n92    = { 0, 1, sl92 };
static const oid_search_link sl91[] = { { 38, &n92 } };
static const oid_search_node n91    = { 0, 1, sl91 };
static const oid_search_link sl90[] = { { 146, &n91 } };
static const oid_search_node n90    = { 0, 1, sl90 };
static const oid_search_node n47    = { ID_HASH_STREEBOG256, 0, NULL }; // 1.2.643.7.1.1.2.2
static const oid_search_node n48    = { ID_HASH_STREEBOG512, 0, NULL }; // 1.2.643.7.1.1.2.3
static const oid_search_link sl46[] = { { 2, &n47 }, { 3, &n48 } };
static const oid_search_node n46    = { 0, 2, sl46 };
static const oid_search_link sl45[] = { { 2, &n46 } };
static const oid_search_node n45    = { 0, 1, sl45 };
static const oid_search_link sl44[] = { { 1, &n45 } };
static const oid_search_node n44    = { 0, 1, sl44 };
static const oid_search_link sl43[] = { { 1, &n44 } };
static const oid_search_node n43    = { 0, 1, sl43 };
static const oid_search_link sl42[] = { { 7, &n43 } };
static const oid_search_node n42    = { 0, 1, sl42 };
static const oid_search_link sl41[] = { { 3, &n42 } };
static const oid_search_node n41    = { 0, 1, sl41 };
static const oid_search_node n9     = { ID_RSA, 0, NULL }; // 1.2.840.113549.1.1.1
static const oid_search_node n49    = { ID_SIGN_RSA_MD2, 0, NULL }; // 1.2.840.113549.1.1.2
static const oid_search_node n50    = { ID_SIGN_RSA_MD5, 0, NULL }; // 1.2.840.113549.1.1.4
static const oid_search_node n51    = { ID_SIGN_RSA_SHA1, 0, NULL }; // 1.2.840.113549.1.1.5
static const oid_search_node n72    = { ID_MGF1, 0, NULL }; // 1.2.840.113549.1.1.8
static const oid_search_node n14    = { ID_RSASSA_PSS, 0, NULL }; // 1.2.840.113549.1.1.10
static const oid_search_node n53    = { ID_SIGN_RSA_SHA256, 0, NULL }; // 1.2.840.113549.1.1.11
static const oid_search_node n54    = { ID_SIGN_RSA_SHA384, 0, NULL }; // 1.2.840.113549.1.1.12
static const oid_search_node n55    = { ID_SIGN_RSA_SHA512, 0, NULL }; // 1.2.840.113549.1.1.13
static const oid_search_node n52    = { ID_SIGN_RSA_SHA224, 0, NULL }; // 1.2.840.113549.1.1.14
static const oid_search_node n56    = { ID_SIGN_RSA_SHA512_224, 0, NULL }; // 1.2.840.113549.1.1.15
static const oid_search_node n57    = { ID_SIGN_RSA_SHA512_256, 0, NULL }; // 1.2.840.113549.1.1.16
static const oid_search_link sl8[]  = { { 1, &n9 }, { 2, &n49 }, { 4, &n50 }, { 5, &n51 }, { 8, &n72 }, { 10, &n14 }, { 11, &n53 }, { 12, &n54 }, { 13, &n55 }, { 14, &n52 }, { 15, &n56 }, { 16, &n57 } };
static const oid_search_node n8     = { 0, 12, sl8 };
static const oid_search_node n101   = { ID_AT_EMAIL_ADDRESS, 0, NULL }; // 1.2.840.113549.1.9.1
static const oid_search_link sl100[] = { { 1, &n101 } };
static const oid_search_node n100   = { 0, 1, sl100 };
static const oid_search_link sl7[]  = { { 1, &n8 }, { 9, &n100 } };
static const oid_search_node n7     = { 0, 2, sl7 };
static const oid_search_node n16    = { ID_HASH_MD2, 0, NULL }; // 1.2.840.113549.2.2
static const oid_search_node n17    = { ID_HASH_MD5, 0, NULL }; // 1.2.840.113549.2.5
static const oid_search_link sl15[] = { { 2, &n16 }, { 5, &n17 } };
static const oid_search_node n15    = { 0, 2, sl15 };
static const oid_search_link sl6[]  = { { 1, &n7 }, { 2, &n15 } };
static const oid_search_node n6     = { 0, 2, sl6 };
static const oid_search_link sl5[]  = { { 13, &n6 } };
static const oid_search_node n5     = { 0, 1, sl5 };
static const oid_search_link sl4[]  = { { 247, &n5 } };
static const oid_search_node n4     = { 0, 1, sl4 };
static const oid_search_node n13    = { ID_DSA, 0, NULL }; // 1.2.840.10040.4.1
static const oid_search_node n63    = { ID_SIGN_DSA_SHA1, 0, NULL }; // 1.2.840.10040.4.3
static const oid_search_link sl12[] = { { 1, &n13 }, { 3, &n63 } };
static const oid_search_node n12    = { 0, 2, sl12 };
static const oid_search_link sl11[] = { { 4, &n12 } };
static const oid_search_node n11    = { 0, 1, sl11 };
static const oid_search_link sl10[] = { { 56, &n11 } };
static const oid_search_node n10    = { 0, 1, sl10 };
static const oid_search_link sl3[]  = { { 134, &n4 }, { 206, &n10 } };
static const oid_search_node n3     = { 0, 2, sl3 };
static const oid_search_link sl2[]  = { { 72, &n3 } };
static const oid_search_node n2     = { 0, 1, sl2 };
static const oid_search_link sl1[]  = { { 133, &n41 }, { 134, &n2 } };
static const oid_search_node n1     = { 0, 2, sl1 };
static const oid_search_node n22    = { ID_HASH_SHA1, 0, NULL }; // 1.3.14.3.2.26
static const oid_search_link sl21[] = { { 26, &n22 } };
static const oid_search_node n21    = { 0, 1, sl21 };
static const oid_search_link sl20[] = { { 2, &n21 } };
static const oid_search_node n20    = { 0, 1, sl20 };
static const oid_search_link sl19[] = { { 3, &n20 } };
static const oid_search_node n19    = { 0, 1, sl19 };
static const oid_search_link sl18[] = { { 14, &n19 } };
static const oid_search_node n18    = { 0, 1, sl18 };
static const oid_search_node n75    = { ID_AT_COMMON_NAME, 0, NULL }; // 2.5.4.3
static const oid_search_node n77    = { ID_AT_SURNAME, 0, NULL }; // 2.5.4.4
static const oid_search_node n88    = { ID_AT_SERIAL_NUMBER, 0, NULL }; // 2.5.4.5
static const oid_search_node n87    = { ID_AT_COUNTRY_NAME, 0, NULL }; // 2.5.4.6
static const oid_search_node n81    = { ID_AT_LOCALITY_NAME, 0, NULL }; // 2.5.4.7
static const oid_search_node n82    = { ID_AT_STATE_OR_PROVINCE_NAME, 0, NULL }; // 2.5.4.8
static const oid_search_node n83    = { ID_AT_ORGANIZATION_NAME, 0, NULL }; // 2.5.4.10
static const oid_search_node n84    = { ID_AT_ORGANIZATIONAL_UNIT_NAME, 0, NULL }; // 2.5.4.11
static const oid_search_node n85    = { ID_AT_TITLE, 0, NULL }; // 2.5.4.12
static const oid_search_node n76    = { ID_AT_NAME, 0, NULL }; // 2.5.4.41
static const oid_search_node n78    = { ID_AT_GIVEN_NAME, 0, NULL }; // 2.5.4.42
static const oid_search_node n79    = { ID_AT_INITIALS, 0, NULL }; // 2.5.4.43
static const oid_search_node n80    = { ID_AT_GENERATION_QUALIFIER, 0, NULL }; // 2.5.4.44
static const oid_search_node n86    = { ID_AT_DN_QUALIFIER, 0, NULL }; // 2.5.4.46
static const oid_search_node n89    = { ID_AT_PSEUDONYM, 0, NULL }; // 2.5.4.65
static const oid_search_link sl74[] = { { 3, &n75 }, { 4, &n77 }, { 5, &n88 }, { 6, &n87 }, { 7, &n81 }, { 8, &n82 }, { 10, &n83 }, { 11, &n84 }, { 12, &n85 }, { 41, &n76 }, { 42, &n78 }, { 43, &n79 }, { 44, &n80 }, { 46, &n86 }, { 65, &n89 } };
static const oid_search_node n74    = { 0, 15, sl74 };
static const oid_search_link sl73[] = { { 4, &n74 } };
static const oid_search_node n73    = { 0, 1, sl73 };
static const oid_search_node n31    = { ID_HASH_SHA256, 0, NULL }; // 2.16.840.1.101.3.4.2.1
static const oid_search_node n32    = { ID_HASH_SHA384, 0, NULL }; // 2.16.840.1.101.3.4.2.2
static const oid_search_node n33    = { ID_HASH_SHA512, 0, NULL }; // 2.16.840.1.101.3.4.2.3
static const oid_search_node n34    = { ID_HASH_SHA224, 0, NULL }; // 2.16.840.1.101.3.4.2.4
static const oid_search_node n35    = { ID_HASH_SHA512_224, 0, NULL }; // 2.16.840.1.101.3.4.2.5
static const oid_search_node n36    = { ID_HASH_SHA512_256, 0, NULL }; // 2.16.840.1.101.3.4.2.6
static const oid_search_node n37    = { ID_HASH_SHA3_224, 0, NULL }; // 2.16.840.1.101.3.4.2.7
static const oid_search_node n38    = { ID_HASH_SHA3_256, 0, NULL }; // 2.16.840.1.101.3.4.2.8
static const oid_search_node n39    = { ID_HASH_SHA3_384, 0, NULL }; // 2.16.840.1.101.3.4.2.9
static const oid_search_node n40    = { ID_HASH_SHA3_512, 0, NULL }; // 2.16.840.1.101.3.4.2.10
static const oid_search_link sl30[] = { { 1, &n31 }, { 2, &n32 }, { 3, &n33 }, { 4, &n34 }, { 5, &n35 }, { 6, &n36 }, { 7, &n37 }, { 8, &n38 }, { 9, &n39 }, { 10, &n40 } };
static const oid_search_node n30    = { 0, 10, sl30 };
static const oid_search_node n64    = { ID_SIGN_DSA_SHA224, 0, NULL }; // 2.16.840.1.101.3.4.3.1
static const oid_search_node n65    = { ID_SIGN_DSA_SHA256, 0, NULL }; // 2.16.840.1.101.3.4.3.2
static const oid_search_node n66    = { ID_SIGN_DSA_SHA384, 0, NULL }; // 2.16.840.1.101.3.4.3.3
static const oid_search_node n67    = { ID_SIGN_DSA_SHA512, 0, NULL }; // 2.16.840.1.101.3.4.3.4
static const oid_search_node n68    = { ID_SIGN_DSA_SHA3_224, 0, NULL }; // 2.16.840.1.101.3.4.3.5
static const oid_search_node n69    = { ID_SIGN_DSA_SHA3_256, 0, NULL }; // 2.16.840.1.101.3.4.3.6
static const oid_search_node n70    = { ID_SIGN_DSA_SHA3_384, 0, NULL }; // 2.16.840.1.101.3.4.3.7
static const oid_search_node n71    = { ID_SIGN_DSA_SHA3_512, 0, NULL }; // 2.16.840.1.101.3.4.3.8
static const oid_search_node n59    = { ID_SIGN_RSA_SHA3_224, 0, NULL }; // 2.16.840.1.101.3.4.3.13
static const oid_search_node n60    = { ID_SIGN_RSA_SHA3_256, 0, NULL }; // 2.16.840.1.101.3.4.3.14
static const oid_search_node n61    = { ID_SIGN_RSA_SHA3_384, 0, NULL }; // 2.16.840.1.101.3.4.3.15
static const oid_search_node n62    = { ID_SIGN_RSA_SHA3_512, 0, NULL }; // 2.16.840.1.101.3.4.3.16
static const oid_search_link sl58[] = { { 1, &n64 }, { 2, &n65 }, { 3, &n66 }, { 4, &n67 }, { 5, &n68 }, { 6, &n69 }, { 7, &n70 }, { 8, &n71 }, { 13, &n59 }, { 14, &n60 }, { 15, &n61 }, { 16, &n62 } };
static const oid_search_node n58    = { 0, 12, sl58 };
static const oid_search_link sl29[] = { { 2, &n30 }, { 3, &n58 } };
static const oid_search_node n29    = { 0, 2, sl29 };
static const oid_search_link sl28[] = { { 4, &n29 } };
static const oid_search_node n28    = { 0, 1, sl28 };
static const oid_search_link sl27[] = { { 3, &n28 } };
static const oid_search_node n27    = { 0, 1, sl27 };
static const oid_search_link sl26[] = { { 101, &n27 } };
static const oid_search_node n26    = { 0, 1, sl26 };
static const oid_search_link sl25[] = { { 1, &n26 } };
static const oid_search_node n25    = { 0, 1, sl25 };
static const oid_search_link sl24[] = { { 72, &n25 } };
static const oid_search_node n24    = { 0, 1, sl24 };
static const oid_search_link sl23[] = { { 134, &n24 } };
static const oid_search_node n23    = { 0, 1, sl23 };
static const oid_search_link sl0[]  = { { 9, &n90 }, { 42, &n1 }, { 43, &n18 }, { 85, &n73 }, { 96, &n23 } };
static const oid_search_node n0     = { 0, 5, sl0 };

#include "oid_search.inc"
